image: Visual Studio 2017
# Build script
init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - cd Build
  - ps: .\build.ps1 -Script build.csx -Configuration Release -Target AppVeyor

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - master
    - dev
    - /r/.*/
    - /release/.*/
    - /hotfix/.*/

# Build cache
cache:
  - Build/tools -> Build/build.csx